### ISSUE TITLE
Running the minted modules tests should be an author test

### ISSUE THREAD

**Issue by colinnewell** [OpusVL/Dist-Zilla-MintingProfile-FB11#2]
The tests are very definitely a good idea, but the installer of the module shouldn't require the modules that the created module depends on.  This means that tests might not pass in the test run.

I think we should probably also ensure tests are run on release (including the author tests) so that we do check we are running these tests before releasing.

**Comment by Altreus** [comment]
Passing this over to #8 so we can generally improve the tests
